In [1]:
# !pip install pandas
import pandas as pd

/tmp/ipykernel_10039/2326295348.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
dataFrame = pd.read_csv("./data/spam.csv", encoding='latin-1')

In [18]:
print(dataFrame["Unnamed: 2"].notna())

KeyError: 'Unnamed: 2'

In [4]:
isNaN = dataFrame.isnull()

print(isNaN)
print("null count", isNaN.sum())

         v1     v2  Unnamed: 2  Unnamed: 3  Unnamed: 4
0     False  False        True        True        True
1     False  False        True        True        True
2     False  False        True        True        True
3     False  False        True        True        True
4     False  False        True        True        True
...     ...    ...         ...         ...         ...
5567  False  False        True        True        True
5568  False  False        True        True        True
5569  False  False        True        True        True
5570  False  False        True        True        True
5571  False  False        True        True        True

[5572 rows x 5 columns]
null count v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [5]:
dataFrame.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)

In [6]:
print(dataFrame.isnull().sum())

v1    0
v2    0
dtype: int64

In [7]:
dataFrame["v1"].value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [8]:
dataFrame.describe()
dataFrame.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
dataFrame.rename(columns={"v1": "label", "v2": "text"}, inplace=True)

In [10]:
dataFrame.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
print(dataFrame["text"].duplicated().sum())
duplicates = dataFrame[dataFrame["text"].duplicated(keep="first")]
print(duplicates["text"].head(10))

403
102    As per your request 'Melle Melle (Oru Minnamin...
153    As per your request 'Melle Melle (Oru Minnamin...
206    As I entered my cabin my PA said, '' Happy B'd...
222                               Sorry, I'll call later
325                     No calls..messages..missed calls
338                               Sorry, I'll call later
356    Congratulations ur awarded 500 of CD vouchers ...
443                               Sorry, I'll call later
532                    Gudnite....tc...practice going on
654                         Did u got that persons story
Name: text, dtype: object

In [12]:
# 원본에서 중복 제거 (첫 번째 것만 남기고 나머지 삭제)
dataFrame.drop_duplicates(subset=["text"], keep="first", inplace=True)

# 제거 후 인덱스 재정렬
dataFrame.reset_index(drop=True, inplace=True)

print("현재 남은 중복 개수:", dataFrame["text"].duplicated().sum())

현재 남은 중복 개수: 0

In [17]:
# print(dataFrame.value_counts().sum())
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(dataFrame["text"])

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
5       FreeMsg Hey there darling it's been 3 week's n...
6       Even my brother is not like to speak with me. ...
7       As per your request 'Melle Melle (Oru Minnamin...
8       WINNER!! As a valued network customer you have...
9       Had your mobile 11 months or more? U R entitle...
10      I'm gonna be home soon and i don't want to tal...
11      SIX chances to win CASH! From 100 to 20,000 po...
12      URGENT! You have won a 1 week FREE membership ...
13      I've been searching for the right words to tha...
14                    I HAVE A DATE ON SUNDAY WITH WILL!!
15      XXXMobileMovieClub: To use your credit, click ...
16                             Oh k...i'm watching here:)
17      Eh u remember how 2 spell his name... Yes i di...
18      Fine if thatåÕs the way u feel. ThatåÕs the wa...
19      England v Macedonia - dont miss the goals/team...
20              Is that seriously how you spell his name?
21      IÛ÷m going to try for 2 months ha ha only joking
22      So Ì_ pay first lar... Then when is da stock c...
23      Aft i finish my lunch then i go str down lor. ...
24      Ffffffffff. Alright no way I can meet up with ...
25      Just forced myself to eat a slice. I'm really ...
26                         Lol your always so convincing.
27      Did you catch the bus ? Are you frying an egg ...
28      I'm back &amp; we're packing the car now, I'll...
29      Ahhh. Work. I vaguely remember that! What does...
30      Wait that's still not all that clear, were you...
31      Yeah he got in at 2 and was v apologetic. n ha...
32                          K tell me anything about you.
33      For fear of fainting with the of all that hous...
34      Thanks for your subscription to Ringtone UK yo...
35      Yup... Ok i go home look at the timings then i...
36        Oops, I'll let you know when my roommate's done
37                           I see the letter B on my car
38                            Anything lor... U decide...
39      Hello! How's you and how did saturday go? I wa...
40      Pls go ahead with watts. I just wanted to be s...
41      Did I forget to tell you ? I want you , I need...
42      07732584351 - Rodger Burns - MSG = We tried to...
43                                    WHO ARE YOU SEEING?
44      Great! I hope you like your man well endowed. ...
45                       No calls..messages..missed calls
46          Didn't you get hep b immunisation in nigeria.
47                        Fair enough, anything going on?
48      Yeah hopefully, if tyler can't do it I could m...
49      U don't know how stubborn I am. I didn't even ...
50      What you thinked about me. First time you saw ...
51      A gram usually runs like  &lt;#&gt; , a half e...
52      K fyi x has a ride early tomorrow morning but ...
53      Wow. I never realized that you were so embaras...
54      SMS. ac Sptv: The New Jersey Devils and the De...
55      Do you know what Mallika Sherawat did yesterda...
56      Congrats! 1 year special cinema pass for 2 is ...
57                     Sorry, I'll call later in meeting.
58                                 Tell where you reached
59               Yes..gauti and sehwag out of odi series.
60      Your gonna have to pick up a $1 burger for you...
61       Ha ha ha good joke. Girls are situation seekers.
62                              Its a part of checking IQ
63      Sorry my roommates took forever, it ok if I co...
64      Ok lar i double check wif da hair dresser alre...
65      As a valued customer, I am pleased to advise y...
66      Today is \song dedicated day..\" Which song wi...
67      Urgent UR awarded a complimentary trip to Euro...
68      Did you hear about the new \Divorce Barbie\"? ...
69                     I plane to give on this month end.
70         Wah lucky man... Then can save money... Hee...
71                          Finished class where are you.
72          HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX
73             K..k:)where are you?how did you performed?
74                                   U can call me now...
75            I am waiting machan. Call me once you free.
76      Thats cool. i am a gentleman and will treat yo...
77      I like you peoples very much:) but am very shy...
78             Does not operate after  &lt;#&gt;  or what
79      Its not the same here. Still looking for a job...
80                                 Sorry, I'll call later
81                       K. Did you call me just now ah?
82                       Ok i am on the way to home hi hi
83                   You will be in the place of that man
84                                         Yup next stop.
85      I call you later, don't have network. If urgnt...
86      For real when u getting on yo? I only need 2 m...
87      Yes I started to send requests to make it but ...
88             I'm really not up to it still tonight babe
89              Ela kano.,il download, come wen ur free..
90      Yeah do! DonÛ÷t stand to close tho- youÛ÷ll ...
91      Sorry to be a pain. Is it ok if we meet anothe...
92      Smile in Pleasure Smile in Pain Smile when tro...
93      Please call our customer service representativ...
94      Havent planning to buy later. I check already ...
95      Your free ringtone is waiting to be collected....
96                      Watching telugu movie..wat abt u?
97      i see. When we finish we have loads of loans t...
98      Hi. Wk been ok - on hols now! Yes on for a bit...
99      Please don't text me anymore. I have nothing e...
100     Okay name ur price as long as its legal! Wen c...
101     I'm still looking for a car to buy. And have n...
102     wow. You're right! I didn't mean to do that. I...
103          Umma my life and vava umma love you lot dear
104     Thanks a lot for your wishes on my birthday. T...
105           Aight, I'll hit you up when I get some cash
106     How would my ip address test that considering ...
107     I know! Grumpy old people. My mom was like you...
108                        Dont worry. I guess he's busy.
109              What is the plural of the noun research?
110                       Going for dinner.msg you after.
111     I'm ok wif it cos i like 2 try new things. But...
112     GENT! We are trying to contact you. Last weeke...
113     Wa, ur openin sentence very formal... Anyway, ...
114     As I entered my cabin my PA said, '' Happy B'd...
115     You are a winner U have been specially selecte...
116     Goodo! Yes we must speak friday - egg-potato r...
117     Hmm...my uncle just informed me that he's payi...
118     PRIVATE! Your 2004 Account Statement for 07742...
119     URGENT! Your Mobile No. was awarded å£2000 Bon...
120     here is my new address -apples&pairs&all that ...
121     Todays Voda numbers ending 7548 are selected t...
122     I am going to sao mu today. Will be done only ...
123              ÌÏ predict wat time Ì_'ll finish buying?
124                                  Good stuff, will do.
125     Just so that you know,yetunde hasn't sent mone...
126                                Are you there in room.
127     HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R B...
128                          K..k:)how much does it cost?
129                                             I'm home.
130               Dear, will call Tmorrow.pls accomodate.
131                             First answer my question.
132     Sunshine Quiz Wkly Q! Win a top Sony DVD playe...
133     Want 2 get laid tonight? Want real Dogging loc...
134                I only haf msn. It's yijue@hotmail.com
135                    He is there. You call and meet him
136        No no. I will check all rooms befor activities
137     You'll not rcv any more msgs from the chat svc...
138     Got c... I lazy to type... I forgot Ì_ in lect...
139                     K, text me when you're on the way
140                           Sir, Waiting for your mail.
141     A swt thought: \Nver get tired of doing little...
142            I know you are. Can you pls open the back?
143                             Yes see ya not on the dot
144      Whats the staff name who is taking class for us?
145     FreeMsg Why haven't you replied to my text? I'...
146     Ummma.will call after check in.our life will b...
147                     K..i deleted my contact that why?
148                        Sindu got job in birla soft ..
149         The wine is flowing and i'm i have nevering..
150     Yup i thk cine is better cos no need 2 go down...
151                             Ok... Ur typical reply...
152     You are everywhere dirt, on the floor, the win...
153                          Aaooooright are you at work?
154                           I'm leaving my house now...
155     Hello, my love. What are you doing? Did you ge...
156     Customer service annoncement. You have a New Y...
157     You are a winner U have been specially selecte...
158     Keep yourself safe for me because I need you a...
159     New car and house for my parents.:)i have only...
160     I'm so in love with you. I'm excited each day ...
161     -PLS STOP bootydelious (32/F) is inviting you ...
162     BangBabes Ur order is on the way. U SHOULD rec...
163     I place all ur points on e cultures module alr...
164     URGENT! We are trying to contact you. Last wee...
165     Hi frnd, which is best way to avoid missunders...
166     Great escape. I fancy the bridge but needs her...
167     Yes :)it completely in out of form:)clark also...
168     Sir, I need AXIS BANK account no and bank addr...
169     Hmmm.. Thk sure got time to hop ard... Ya, can...
170                     What time you coming down later?
171     Bloody hell, cant believe you forgot my surnam...
172     Well, i'm gonna finish my bath now. Have a goo...
173     Let me know when you've got the money so carlo...
174                            U still going to the mall?
175     Turns out my friends are staying for the whole...
176     Text her. If she doesnt reply let me know so i...
177     Hi! You just spoke to MANEESHA V. We'd like to...
178     You lifted my hopes with the offer of money. I...
179                               Lol no. U can trust me.
180     ok. I am a gentleman and will treat you with d...
181                              He will, you guys close?
182                            Going on nothing great.bye
183     Hello handsome ! Are you finding that job ? No...
184                    Haha awesome, be there in a minute
185     Please call our customer service representativ...
186     Have you got Xmas radio times. If not i will g...
187     I jus reached home. I go bathe first. But my s...
188     Are you unique enough? Find out from 30th Augu...
189     I'm sorry. I've joined the league of people th...
190                 Hi :)finally i completed the course:)
191     It will stop on itself. I however suggest she ...
192     How are you doing? Hope you've settled in for ...
193                          Gud mrng dear hav a nice day
194                          Did u got that persons story
195     is your hamster dead? Hey so tmr i meet you at...
196     Hi its Kate how is your evening? I hope i can ...
197              Found it, ENC  &lt;#&gt; , where you at?
198                          I sent you  &lt;#&gt;  bucks
199     Hello darlin ive finished college now so txt m...
200     Your account has been refilled successfully by...
201                              Goodmorning sleeping ga.
202                             U call me alter at 11 ok.
203     ÌÏ say until like dat i dun buy ericsson oso c...
204                          Aight yo, dats straight dogg
205     You please give us connection today itself bef...
206               Both :) i shoot big loads so get ready!
207     What's up bruv, hope you had a great break. Do...
208                            Home so we can always chat
209                               K:)k:)good:)study well.
210                              Yup... How Ì_ noe leh...
211                       Sounds great! Are you home now?
212     Finally the match heading towards draw as your...
213      Tired. I haven't slept well the past few nights.
214             Easy ah?sen got selected means its good..
215                      I have to take exam with march 3
216     Yeah you should. I think you can use your gt a...
217                             Ok no prob. Take ur time.
218     There is os called ubandu which will run witho...
219     U say leh... Of course nothing happen lar. Not...
220     500 New Mobiles from 2004, MUST GO! Txt: NOKIA...
221     Would really appreciate if you call me. Just n...
222     Will u meet ur dream partner soon? Is ur caree...
223                        Hey company elama po mudyadhu.
224     Life is more strict than teacher... Bcoz Teach...
225                    Dear good morning now only i am up
226     Get down in gandhipuram and walk to cross cut ...
227                 Dear we are going to our rubber place
228                     Sorry battery died, yeah I'm here
229      Yes:)here tv is always available in work place..
230     Text & meet someone sexy today. U can find a d...
231     I have printed it oh. So  &lt;#&gt;  come upst...
232     Or ill be a little closer like at the bus stop...
233                Where are you?when wil you reach here?
234     New Theory: Argument wins d SITUATION, but los...
235     U 447801259231 have a secret admirer who is lo...
236     Tomarrow final hearing on my laptop case so i ...
237         PLEASSSSSSSEEEEEE TEL ME V AVENT DONE SPORTSx
238     Okay. No no, just shining on. That was meant t...
239     Although i told u dat i'm into baig face watch...
240                 U don't remember that old commercial?
241     Too late. I said i have the website. I didn't ...
242                        I asked you to call him now ok
243                       Kallis wont bat in 2nd innings.
244     It didnt work again oh. Ok goodnight then. I.l...
245     Congratulations ur awarded 500 of CD vouchers ...
246          Ranjith cal drpd Deeraj and deepak 5min hold
247     Wen ur lovable bcums angry wid u, dnt take it ...
248                           What you doing?how are you?
249     Ups which is 3days also, and the shipping comp...
250                I'm back, lemme know when you're ready
251     Don't necessarily expect it to be done before ...
252           Mmm so yummy babe ... Nice jolt to the suzy
253                  Where are you lover ? I need you ...
254     We tried to contact you re your reply to our o...
255     IÛ÷m parked next to a MINI!!!! When are you c...
256                                                   Yup
257     Anyway i'm going shopping on my own now. Cos m...
258     MY NO. IN LUTON 0125698789 RING ME IF UR AROUN...
259     Hey I am really horny want to chat or see me n...
260                            Why you Dint come with us.
261                   Same. Wana plan a trip sometme then
262       Not sure yet, still trying to get a hold of him
263     Ur ringtone service has changed! 25 Free credi...
264       The evo. I just had to download flash. Jealous?
265     Ringtone Club: Get the UK singles chart on you...
266     Come to mu, we're sorting out our narcotics si...
267     Night has ended for another day, morning has c...
268     HMV BONUS SPECIAL 500 pounds of genuine HMV vo...
269                 Usf I guess, might as well take 1 car
270                       No objection. My bf not coming.
271                                              Thanx...
272                Tell rob to mack his gf in the theater
273                        Awesome, I'll see you in a bit
274       Just sent it. So what type of food do you like?
275     All done? All handed in? Celebrations in full ...
276                                You got called a tool?
277                                   \Wen u miss someone
278                         Ok. I asked for money how far
279                                               Okie...
280     Yeah I think my usual guy's still passed out f...
281     K, I might come by tonight then if my class le...
282                                                  Ok..
283     hi baby im cruisin with my girl friend what r ...
284     My life Means a lot to me, Not because I love ...
285     Dear,shall mail tonite.busy in the street,shal...
286                 Hey you told your name to gautham ah?
287     Haf u found him? I feel so stupid da v cam was...
288                                 Oops. 4 got that bit.
289                                Are you this much buzy
290     I accidentally deleted the message. Resend ple...
291     T-Mobile customer you may now claim your FREE ...
292     Unless it's a situation where YOU GO GURL woul...
293     Hurt me... Tease me... Make me cry... But in t...
294     I cant pick the phone right now. Pls send a me...
295     Need a coffee run tomo?Can't believe it's that...
296     Awesome, I remember the last time we got someb...
297     Shit that is really shocking and scary, cant i...
298     Oh and by the way you do have more food in you...
299                              He is a womdarfull actor
300     SMS. ac Blind Date 4U!: Rodds1 is 21/m from Ab...
301     Yup... From what i remb... I think should be c...
302                            Jos ask if u wana meet up?
303     Lol yes. Our friendship is hanging on a thread...
304     TheMob> Check out our newest selection of cont...
305     Where are the garage keys? They aren't on the ...
306     Today is ACCEPT DAY..U Accept me as? Brother S...
307     Think ur smart ? Win å£200 this week in our we...
308     He says he'll give me a call when his friend's...
309     Hi the way I was with u 2day, is the normal wa...
310             You made my day. Do have a great day too.
311                            K.k:)advance happy pongal.
312     Hmmm... Guess we can go 4 kb n power yoga... H...
313        Not really dude, have no friends i'm afraid :(
314     December only! Had your mobile 11mths+? You ar...
315                               Coffee cake, i guess...
316     Merry Christmas to you too babe, i love ya *ki...
317     Hey... Why dont we just go watch x men and hav...
318     cud u tell ppl im gona b a bit l8 cos 2 buses ...
319     That would be great. We'll be at the Guild. Co...
320                        No problem. How are you doing?
321                       Hi da:)how is the todays class?
322     I'd say that's a good sign but, well, you know...
323                      Cool, text me when you're parked
324     I'm reading the text i just sent you. Its mean...
325                                K.k:)apo k.good movie.
326     Maybe i could get book out tomo then return it...
327     Call Germany for only 1 pence per minute! Call...
328     Any chance you might have had with me evaporat...
329     Valentines Day Special! Win over å£1000 in our...
330         Ta-Daaaaa! I am home babe, are you still up ?
331     Cool. So how come you havent been wined and di...
332                            Just sleeping..and surfing
333             U calling me right? Call my hand phone...
334                          Ok that's great thanx a lot.
335     I take it the post has come then! You must hav...
336                         Where u been hiding stranger?
337                    Am not interested to do like that.
338     My sister cleared two round in birla soft yest...
339                     Gudnite....tc...practice going on
340     Dis is yijue. I jus saw ur mail. In case huimi...
341                       One small prestige problem now.
342     Fancy a shag? I do.Interested? sextextuk.com t...
343     Just checking in on you. Really do miss seeing...

In [20]:
import re

text = dataFrame["text"]
print(text)

def clean_special_chars(text):
    text = re.sub('[^a-zA-Z\s]', '', text)

    text = re.sub('\s+', ' ', text).strip()
    return text

dataFrame['text_clean'] = dataFrame['text'].apply(clean_special_chars)
print(dataFrame[['text', 'text_clean']].head())

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
5       FreeMsg Hey there darling it's been 3 week's n...
6       Even my brother is not like to speak with me. ...
7       As per your request 'Melle Melle (Oru Minnamin...
8       WINNER!! As a valued network customer you have...
9       Had your mobile 11 months or more? U R entitle...
10      I'm gonna be home soon and i don't want to tal...
11      SIX chances to win CASH! From 100 to 20,000 po...
12      URGENT! You have won a 1 week FREE membership ...
13      I've been searching for the right words to tha...
14                    I HAVE A DATE ON SUNDAY WITH WILL!!
15      XXXMobileMovieClub: To use your credit, click ...
16                             Oh k...i'm watching here:)
17      Eh u remember how 2 spell his name... Yes i di...
18      Fine if thatåÕs the way u feel. ThatåÕs the wa...
19      England v Macedonia - dont miss the goals/team...
20              Is that seriously how you spell his name?
21      IÛ÷m going to try for 2 months ha ha only joking
22      So Ì_ pay first lar... Then when is da stock c...
23      Aft i finish my lunch then i go str down lor. ...
24      Ffffffffff. Alright no way I can meet up with ...
25      Just forced myself to eat a slice. I'm really ...
26                         Lol your always so convincing.
27      Did you catch the bus ? Are you frying an egg ...
28      I'm back &amp; we're packing the car now, I'll...
29      Ahhh. Work. I vaguely remember that! What does...
30      Wait that's still not all that clear, were you...
31      Yeah he got in at 2 and was v apologetic. n ha...
32                          K tell me anything about you.
33      For fear of fainting with the of all that hous...
34      Thanks for your subscription to Ringtone UK yo...
35      Yup... Ok i go home look at the timings then i...
36        Oops, I'll let you know when my roommate's done
37                           I see the letter B on my car
38                            Anything lor... U decide...
39      Hello! How's you and how did saturday go? I wa...
40      Pls go ahead with watts. I just wanted to be s...
41      Did I forget to tell you ? I want you , I need...
42      07732584351 - Rodger Burns - MSG = We tried to...
43                                    WHO ARE YOU SEEING?
44      Great! I hope you like your man well endowed. ...
45                       No calls..messages..missed calls
46          Didn't you get hep b immunisation in nigeria.
47                        Fair enough, anything going on?
48      Yeah hopefully, if tyler can't do it I could m...
49      U don't know how stubborn I am. I didn't even ...
50      What you thinked about me. First time you saw ...
51      A gram usually runs like  &lt;#&gt; , a half e...
52      K fyi x has a ride early tomorrow morning but ...
53      Wow. I never realized that you were so embaras...
54      SMS. ac Sptv: The New Jersey Devils and the De...
55      Do you know what Mallika Sherawat did yesterda...
56      Congrats! 1 year special cinema pass for 2 is ...
57                     Sorry, I'll call later in meeting.
58                                 Tell where you reached
59               Yes..gauti and sehwag out of odi series.
60      Your gonna have to pick up a $1 burger for you...
61       Ha ha ha good joke. Girls are situation seekers.
62                              Its a part of checking IQ
63      Sorry my roommates took forever, it ok if I co...
64      Ok lar i double check wif da hair dresser alre...
65      As a valued customer, I am pleased to advise y...
66      Today is \song dedicated day..\" Which song wi...
67      Urgent UR awarded a complimentary trip to Euro...
68      Did you hear about the new \Divorce Barbie\"? ...
69                     I plane to give on this month end.
70         Wah lucky man... Then can save money... Hee...
71                          Finished class where are you.
72          HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX
73             K..k:)where are you?how did you performed?
74                                   U can call me now...
75            I am waiting machan. Call me once you free.
76      Thats cool. i am a gentleman and will treat yo...
77      I like you peoples very much:) but am very shy...
78             Does not operate after  &lt;#&gt;  or what
79      Its not the same here. Still looking for a job...
80                                 Sorry, I'll call later
81                       K. Did you call me just now ah?
82                       Ok i am on the way to home hi hi
83                   You will be in the place of that man
84                                         Yup next stop.
85      I call you later, don't have network. If urgnt...
86      For real when u getting on yo? I only need 2 m...
87      Yes I started to send requests to make it but ...
88             I'm really not up to it still tonight babe
89              Ela kano.,il download, come wen ur free..
90      Yeah do! DonÛ÷t stand to close tho- youÛ÷ll ...
91      Sorry to be a pain. Is it ok if we meet anothe...
92      Smile in Pleasure Smile in Pain Smile when tro...
93      Please call our customer service representativ...
94      Havent planning to buy later. I check already ...
95      Your free ringtone is waiting to be collected....
96                      Watching telugu movie..wat abt u?
97      i see. When we finish we have loads of loans t...
98      Hi. Wk been ok - on hols now! Yes on for a bit...
99      Please don't text me anymore. I have nothing e...
100     Okay name ur price as long as its legal! Wen c...
101     I'm still looking for a car to buy. And have n...
102     wow. You're right! I didn't mean to do that. I...
103          Umma my life and vava umma love you lot dear
104     Thanks a lot for your wishes on my birthday. T...
105           Aight, I'll hit you up when I get some cash
106     How would my ip address test that considering ...
107     I know! Grumpy old people. My mom was like you...
108                        Dont worry. I guess he's busy.
109              What is the plural of the noun research?
110                       Going for dinner.msg you after.
111     I'm ok wif it cos i like 2 try new things. But...
112     GENT! We are trying to contact you. Last weeke...
113     Wa, ur openin sentence very formal... Anyway, ...
114     As I entered my cabin my PA said, '' Happy B'd...
115     You are a winner U have been specially selecte...
116     Goodo! Yes we must speak friday - egg-potato r...
117     Hmm...my uncle just informed me that he's payi...
118     PRIVATE! Your 2004 Account Statement for 07742...
119     URGENT! Your Mobile No. was awarded å£2000 Bon...
120     here is my new address -apples&pairs&all that ...
121     Todays Voda numbers ending 7548 are selected t...
122     I am going to sao mu today. Will be done only ...
123              ÌÏ predict wat time Ì_'ll finish buying?
124                                  Good stuff, will do.
125     Just so that you know,yetunde hasn't sent mone...
126                                Are you there in room.
127     HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R B...
128                          K..k:)how much does it cost?
129                                             I'm home.
130               Dear, will call Tmorrow.pls accomodate.
131                             First answer my question.
132     Sunshine Quiz Wkly Q! Win a top Sony DVD playe...
133     Want 2 get laid tonight? Want real Dogging loc...
134                I only haf msn. It's yijue@hotmail.com
135                    He is there. You call and meet him
136        No no. I will check all rooms befor activities
137     You'll not rcv any more msgs from the chat svc...
138     Got c... I lazy to type... I forgot Ì_ in lect...
139                     K, text me when you're on the way
140                           Sir, Waiting for your mail.
141     A swt thought: \Nver get tired of doing little...
142            I know you are. Can you pls open the back?
143                             Yes see ya not on the dot
144      Whats the staff name who is taking class for us?
145     FreeMsg Why haven't you replied to my text? I'...
146     Ummma.will call after check in.our life will b...
147                     K..i deleted my contact that why?
148                        Sindu got job in birla soft ..
149         The wine is flowing and i'm i have nevering..
150     Yup i thk cine is better cos no need 2 go down...
151                             Ok... Ur typical reply...
152     You are everywhere dirt, on the floor, the win...
153                          Aaooooright are you at work?
154                           I'm leaving my house now...
155     Hello, my love. What are you doing? Did you ge...
156     Customer service annoncement. You have a New Y...
157     You are a winner U have been specially selecte...
158     Keep yourself safe for me because I need you a...
159     New car and house for my parents.:)i have only...
160     I'm so in love with you. I'm excited each day ...
161     -PLS STOP bootydelious (32/F) is inviting you ...
162     BangBabes Ur order is on the way. U SHOULD rec...
163     I place all ur points on e cultures module alr...
164     URGENT! We are trying to contact you. Last wee...
165     Hi frnd, which is best way to avoid missunders...
166     Great escape. I fancy the bridge but needs her...
167     Yes :)it completely in out of form:)clark also...
168     Sir, I need AXIS BANK account no and bank addr...
169     Hmmm.. Thk sure got time to hop ard... Ya, can...
170                     What time you coming down later?
171     Bloody hell, cant believe you forgot my surnam...
172     Well, i'm gonna finish my bath now. Have a goo...
173     Let me know when you've got the money so carlo...
174                            U still going to the mall?
175     Turns out my friends are staying for the whole...
176     Text her. If she doesnt reply let me know so i...
177     Hi! You just spoke to MANEESHA V. We'd like to...
178     You lifted my hopes with the offer of money. I...
179                               Lol no. U can trust me.
180     ok. I am a gentleman and will treat you with d...
181                              He will, you guys close?
182                            Going on nothing great.bye
183     Hello handsome ! Are you finding that job ? No...
184                    Haha awesome, be there in a minute
185     Please call our customer service representativ...
186     Have you got Xmas radio times. If not i will g...
187     I jus reached home. I go bathe first. But my s...
188     Are you unique enough? Find out from 30th Augu...
189     I'm sorry. I've joined the league of people th...
190                 Hi :)finally i completed the course:)
191     It will stop on itself. I however suggest she ...
192     How are you doing? Hope you've settled in for ...
193                          Gud mrng dear hav a nice day
194                          Did u got that persons story
195     is your hamster dead? Hey so tmr i meet you at...
196     Hi its Kate how is your evening? I hope i can ...
197              Found it, ENC  &lt;#&gt; , where you at?
198                          I sent you  &lt;#&gt;  bucks
199     Hello darlin ive finished college now so txt m...
200     Your account has been refilled successfully by...
201                              Goodmorning sleeping ga.
202                             U call me alter at 11 ok.
203     ÌÏ say until like dat i dun buy ericsson oso c...
204                          Aight yo, dats straight dogg
205     You please give us connection today itself bef...
206               Both :) i shoot big loads so get ready!
207     What's up bruv, hope you had a great break. Do...
208                            Home so we can always chat
209                               K:)k:)good:)study well.
210                              Yup... How Ì_ noe leh...
211                       Sounds great! Are you home now?
212     Finally the match heading towards draw as your...
213      Tired. I haven't slept well the past few nights.
214             Easy ah?sen got selected means its good..
215                      I have to take exam with march 3
216     Yeah you should. I think you can use your gt a...
217                             Ok no prob. Take ur time.
218     There is os called ubandu which will run witho...
219     U say leh... Of course nothing happen lar. Not...
220     500 New Mobiles from 2004, MUST GO! Txt: NOKIA...
221     Would really appreciate if you call me. Just n...
222     Will u meet ur dream partner soon? Is ur caree...
223                        Hey company elama po mudyadhu.
224     Life is more strict than teacher... Bcoz Teach...
225                    Dear good morning now only i am up
226     Get down in gandhipuram and walk to cross cut ...
227                 Dear we are going to our rubber place
228                     Sorry battery died, yeah I'm here
229      Yes:)here tv is always available in work place..
230     Text & meet someone sexy today. U can find a d...
231     I have printed it oh. So  &lt;#&gt;  come upst...
232     Or ill be a little closer like at the bus stop...
233                Where are you?when wil you reach here?
234     New Theory: Argument wins d SITUATION, but los...
235     U 447801259231 have a secret admirer who is lo...
236     Tomarrow final hearing on my laptop case so i ...
237         PLEASSSSSSSEEEEEE TEL ME V AVENT DONE SPORTSx
238     Okay. No no, just shining on. That was meant t...
239     Although i told u dat i'm into baig face watch...
240                 U don't remember that old commercial?
241     Too late. I said i have the website. I didn't ...
242                        I asked you to call him now ok
243                       Kallis wont bat in 2nd innings.
244     It didnt work again oh. Ok goodnight then. I.l...
245     Congratulations ur awarded 500 of CD vouchers ...
246          Ranjith cal drpd Deeraj and deepak 5min hold
247     Wen ur lovable bcums angry wid u, dnt take it ...
248                           What you doing?how are you?
249     Ups which is 3days also, and the shipping comp...
250                I'm back, lemme know when you're ready
251     Don't necessarily expect it to be done before ...
252           Mmm so yummy babe ... Nice jolt to the suzy
253                  Where are you lover ? I need you ...
254     We tried to contact you re your reply to our o...
255     IÛ÷m parked next to a MINI!!!! When are you c...
256                                                   Yup
257     Anyway i'm going shopping on my own now. Cos m...
258     MY NO. IN LUTON 0125698789 RING ME IF UR AROUN...
259     Hey I am really horny want to chat or see me n...
260                            Why you Dint come with us.
261                   Same. Wana plan a trip sometme then
262       Not sure yet, still trying to get a hold of him
263     Ur ringtone service has changed! 25 Free credi...
264       The evo. I just had to download flash. Jealous?
265     Ringtone Club: Get the UK singles chart on you...
266     Come to mu, we're sorting out our narcotics si...
267     Night has ended for another day, morning has c...
268     HMV BONUS SPECIAL 500 pounds of genuine HMV vo...
269                 Usf I guess, might as well take 1 car
270                       No objection. My bf not coming.
271                                              Thanx...
272                Tell rob to mack his gf in the theater
273                        Awesome, I'll see you in a bit
274       Just sent it. So what type of food do you like?
275     All done? All handed in? Celebrations in full ...
276                                You got called a tool?
277                                   \Wen u miss someone
278                         Ok. I asked for money how far
279                                               Okie...
280     Yeah I think my usual guy's still passed out f...
281     K, I might come by tonight then if my class le...
282                                                  Ok..
283     hi baby im cruisin with my girl friend what r ...
284     My life Means a lot to me, Not because I love ...
285     Dear,shall mail tonite.busy in the street,shal...
286                 Hey you told your name to gautham ah?
287     Haf u found him? I feel so stupid da v cam was...
288                                 Oops. 4 got that bit.
289                                Are you this much buzy
290     I accidentally deleted the message. Resend ple...
291     T-Mobile customer you may now claim your FREE ...
292     Unless it's a situation where YOU GO GURL woul...
293     Hurt me... Tease me... Make me cry... But in t...
294     I cant pick the phone right now. Pls send a me...
295     Need a coffee run tomo?Can't believe it's that...
296     Awesome, I remember the last time we got someb...
297     Shit that is really shocking and scary, cant i...
298     Oh and by the way you do have more food in you...
299                              He is a womdarfull actor
300     SMS. ac Blind Date 4U!: Rodds1 is 21/m from Ab...
301     Yup... From what i remb... I think should be c...
302                            Jos ask if u wana meet up?
303     Lol yes. Our friendship is hanging on a thread...
304     TheMob> Check out our newest selection of cont...
305     Where are the garage keys? They aren't on the ...
306     Today is ACCEPT DAY..U Accept me as? Brother S...
307     Think ur smart ? Win å£200 this week in our we...
308     He says he'll give me a call when his friend's...
309     Hi the way I was with u 2day, is the normal wa...
310             You made my day. Do have a great day too.
311                            K.k:)advance happy pongal.
312     Hmmm... Guess we can go 4 kb n power yoga... H...
313        Not really dude, have no friends i'm afraid :(
314     December only! Had your mobile 11mths+? You ar...
315                               Coffee cake, i guess...
316     Merry Christmas to you too babe, i love ya *ki...
317     Hey... Why dont we just go watch x men and hav...
318     cud u tell ppl im gona b a bit l8 cos 2 buses ...
319     That would be great. We'll be at the Guild. Co...
320                        No problem. How are you doing?
321                       Hi da:)how is the todays class?
322     I'd say that's a good sign but, well, you know...
323                      Cool, text me when you're parked
324     I'm reading the text i just sent you. Its mean...
325                                K.k:)apo k.good movie.
326     Maybe i could get book out tomo then return it...
327     Call Germany for only 1 pence per minute! Call...
328     Any chance you might have had with me evaporat...
329     Valentines Day Special! Win over å£1000 in our...
330         Ta-Daaaaa! I am home babe, are you still up ?
331     Cool. So how come you havent been wined and di...
332                            Just sleeping..and surfing
333             U calling me right? Call my hand phone...
334                          Ok that's great thanx a lot.
335     I take it the post has come then! You must hav...
336                         Where u been hiding stranger?
337                    Am not interested to do like that.
338     My sister cleared two round in birla soft yest...
339                     Gudnite....tc...practice going on
340     Dis is yijue. I jus saw ur mail. In case huimi...
341                       One small prestige problem now.
342     Fancy a shag? I do.Interested? sextextuk.com t...
343     Just checking in on you. Really do miss seeing...